#ifndef MAP_WIDGET_FACTORY_GLOBAL_H
#define MAP_WIDGET_FACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MAP_WIDGET_FACTORY_LIBRARY)
#  define MAP_WIDGET_FACTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MAP_WIDGET_FACTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MAP_WIDGET_FACTORY_GLOBAL_H
