#ifndef CAMERA_WIDGET_FACTORY_GLOBAL_H
#define CAMERA_WIDGET_FACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAMERA_WIDGET_LIBRARY)
#  define CAMERA_WIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CAMERA_WIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMERA_WIDGET_FACTORY_GLOBAL_H
